### ISSUE TITLE
A slew of bugs

### ISSUE THREAD

**Issue by jehnicat** [Wallemations/ss13_artmapper#1]
Hi! I don't know if there's a specific format I should be writing this in, but I use this program pretty frequently, so I figured I might as well just list off some issues I've noticed.

1. The program crashes if you accidentally click anywhere when inputting a location for whatever.
2. Inputs can be so fast that steps are skipped in the color selection phase.
2.5. The game sometimes hits you with the "You have performed the same action too many times in the last minute. Admins have been notified" (or whatever the heck) errors if the program colors too much at once, which when it finally stops, erases all the progress from when it began to when it ended. 
3. Server lag heavily influences the probability of a successful painting.
4. Trying to cancel the program's progress can take a lot of spamming the cancel key to do so.
5. Not being able to restart progress from any point means that a single mistake, no matter how late into the painting, necessitates a full restart.

By and large it's good enough for what it is, but it tends to get a bit frustrating when it messes up.

**Comment by Wallemations** [comment]
> Hi! I don't know if there's a specific format I should be writing this in, but I use this program pretty frequently, so I figured I might as well just list off some issues I've noticed.
> 
> 
> 
> 1. The program crashes if you accidentally click anywhere when inputting a location for whatever.
> 
> 2. Inputs can be so fast that steps are skipped in the color selection phase.
> 
> 2.5. The game sometimes hits you with the "You have performed the same action too many times in the last minute. Admins have been notified" (or whatever the heck) errors if the program colors too much at once, which when it finally stops, erases all the progress from when it began to when it ended. 
> 
> 3. Server lag heavily influences the probability of a successful painting.
> 
> 4. Trying to cancel the program's progress can take a lot of spamming the cancel key to do so.
> 
> 5. Not being able to restart progress from any point means that a single mistake, no matter how late into the painting, necessitates a full restart.
> 
> 
> 
> By and large it's good enough for what it is, but it tends to get a bit frustrating when it messes up.

Hey! Sorry this took so long, I never really expected anyone to actually do anything on this repo lol
1. I'll try to fix the crash with the clicking, idk what could be causing that
2. That's an issue regarding the amount of inputs per second the server allows rather than the mapper itself. I'll see about making it easier to edit the tick rate for the mapper, but there's no real solution for it other than making the mapper go slower
3. The program cancel must be held not pressed, I might have to be more specific with that... I can see if I can figure out a way to make it a single-press rather than a hold, but as I'm not super experienced that might take a bit of work
4. I can see about some sort of progress-saving function to let you either store your current painting progress and continue from there or restart entirely. Might take a bit of tweaking though
